name: Deploy tailwind Project

on:
  push:
    branches:
      - tailwind

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for deployment authentication
      pages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install || echo "No dependencies to install"

      # This is seemingly needed because github pages expects the file to be named specifically index.html
      - name: Create Redirecting index.html
        run: echo '<!DOCTYPE html><html><head><script>window.location.href="turbulentarius.html";</script></head><body><p>If you are not redirected, <a href="turbulentarius.html">click here</a>.</p></body></html>' > index.html
    

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2